# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tu-PyvMIkYQrgM4EOl4eReTMTcTRa4b_
"""

from setuptools import setup

if __name__ == '__main__':
setup(name='trainer', packages=['trainer'])